### ISSUE TITLE
Speed is crazy

### ISSUE THREAD

**Issue by jimz011** [dnguyen800/Quote-of-the-Day-Card#1]
Hi, I have installed this card and it looks really nice so far. However, I do have a problem. It changes quotes every second which makes it nearly impossible to read a quote. Is there anything in the config I can change?

**Comment by dnguyen800** [comment]
Hey, unfortunately I don't have a good idea on how to fix this. I think the quote changes whenever something in Home Assistant refreshes. I'll look into fixes soon, hopefully.

**Comment by PrathikGopal** [comment]
Same here, thank you for looking into it @dnguyen800

**Comment by dnguyen800** [comment]
I tried playing around with some Javascript methods but couldn't figure out a solution. I won't be able to fix unless someone suggests another method.

**Comment by dnguyen800** [comment]
fixed in the latest release.
